// This file is automatically generated, please do not alter it.
// 2025-12-14 00:38:42
#pragma once

inline auto SWIRL_WARP_EFFECT_FRAG_STR =
	"#version 310 es\n"
	"precision mediump float;\n"
	"precision highp int;\n"
	"layout(binding = 1, std140) uniform LocalInfo\n"
	"{\n"
	"    highp float radius;\n"
	"    highp float angle;\n"
	"    highp vec2 center;\n"
	"} localInfo;\n"
	"layout(binding = 0) uniform highp sampler2D uTex;\n"
	"layout(location = 0) in highp vec2 texCoord;\n"
	"layout(location = 0) out highp vec4 FragColor;\n"
	"void main()\n"
	"{\n"
	"    highp vec2 texSize = vec2(textureSize(uTex, 0));\n"
	"    highp float effectRadius = localInfo.radius / texSize.y;\n"
	"    highp float effectAngle = localInfo.angle;\n"
	"    highp vec2 center = localInfo.center / texSize;\n"
	"    highp vec2 uv = texCoord - center;\n"
	"    highp float len = length(uv * vec2(texSize.x / texSize.y, 1.0));\n"
	"    highp float angle = atan(uv.y, uv.x) + (effectAngle * smoothstep(effectRadius, 0.0, len));\n"
	"    highp float radius = length(uv);\n"
	"    highp vec2 cood = vec2(radius * cos(angle), radius * sin(angle)) + center;\n"
	"    FragColor = texture(uTex, cood);\n"
	"}\n"
;