// This file is automatically generated, please do not alter it.
// 2025-12-14 00:38:42
#pragma once

inline auto EXPOSURE_FILTER_PASS_FRAG_STR =
	"#version 410\n"
	"layout(std140) uniform LocalInfo\n"
	"{\n"
	"    float exposure;\n"
	"} localInfo;\n"
	"uniform sampler2D uTex;\n"
	"layout(location = 0) in vec2 texCoord;\n"
	"layout(location = 0) out vec4 FragColor;\n"
	"vec3 exposureCurve(vec3 c, float e)\n"
	"{\n"
	"    return vec3(1.0) - exp((-c) * e);\n"
	"}\n"
	"void main()\n"
	"{\n"
	"    vec4 color = texture(uTex, texCoord);\n"
	"    vec3 param = color.xyz;\n"
	"    float param_1 = localInfo.exposure;\n"
	"    vec3 _50 = exposureCurve(param, param_1);\n"
	"    color.x = _50.x;\n"
	"    color.y = _50.y;\n"
	"    color.z = _50.z;\n"
	"    FragColor = color;\n"
	"}\n"
;