// This file is automatically generated, please do not alter it.
// 2025-12-14 00:38:42
#pragma once

inline auto EXPOSURE_FILTER_PASS_FRAG_STR =
	"#version 310 es\n"
	"precision mediump float;\n"
	"precision highp int;\n"
	"layout(binding = 1, std140) uniform LocalInfo\n"
	"{\n"
	"    highp float exposure;\n"
	"} localInfo;\n"
	"layout(binding = 0) uniform highp sampler2D uTex;\n"
	"layout(location = 0) in highp vec2 texCoord;\n"
	"layout(location = 0) out highp vec4 FragColor;\n"
	"highp vec3 exposureCurve(highp vec3 c, highp float e)\n"
	"{\n"
	"    return vec3(1.0) - exp((-c) * e);\n"
	"}\n"
	"void main()\n"
	"{\n"
	"    highp vec4 color = texture(uTex, texCoord);\n"
	"    highp vec3 param = color.xyz;\n"
	"    highp float param_1 = localInfo.exposure;\n"
	"    highp vec3 _50 = exposureCurve(param, param_1);\n"
	"    color.x = _50.x;\n"
	"    color.y = _50.y;\n"
	"    color.z = _50.z;\n"
	"    FragColor = color;\n"
	"}\n"
;