// This file is automatically generated, please do not alter it.
// 2025-11-22 23:47:14
#pragma once

inline auto ROUND_CORNER_PASS_FRAG_STR =
	"#version 310 es\n"
	"precision mediump float;\n"
	"precision highp int;\n"
	"layout(binding = 2, std140) uniform LocalInfo\n"
	"{\n"
	"    highp vec2 resolution;\n"
	"} localInfo;\n"
	"layout(binding = 1) uniform highp sampler2D screenTex;\n"
	"layout(location = 0) out highp vec4 FragColor;\n"
	"void main()\n"
	"{\n"
	"    FragColor = vec4(0.0, 1.0, 0.0, 1.0);\n"
	"}\n"
;