// This file is automatically generated, please do not alter it.
// 2025-07-06 17:42:54
#pragma once

inline auto ROUND_CORNER_PASS_FRAG_STR =
	"#version 310 es"
	"precision mediump float;"
	"precision highp int;"
	"layout(binding = 2, std140) uniform LocalInfo"
	"{"
	"    highp vec2 resolution;"
	"} localInfo;"
	"layout(binding = 1) uniform highp sampler2D screenTex;"
	"layout(location = 0) out highp vec4 FragColor;"
	"void main()"
	"{"
	"    FragColor = vec4(0.0, 1.0, 0.0, 1.0);"
	"}"
;