// This file is automatically generated, please do not alter it.
// 2025-11-30 15:46:03
#pragma once

inline auto DUAL_KAWASE_BLUR_UP_SAMPLE_PASS_FRAG_STR =
	"#version 410\n"
	"layout(std140) uniform LocalInfo\n"
	"{\n"
	"    vec2 iResolution;\n"
	"    vec2 offset;\n"
	"} localInfo;\n"
	"uniform sampler2D texture0;\n"
	"layout(location = 0) out vec4 FragColor;\n"
	"void main()\n"
	"{\n"
	"    vec2 uv = gl_FragCoord.xy / localInfo.iResolution;\n"
	"    vec2 halfpixel = vec2(0.5) / localInfo.iResolution;\n"
	"    vec4 sum = texture(texture0, uv + (vec2((-halfpixel.x) * 2.0, 0.0) * localInfo.offset));\n"
	"    sum += (texture(texture0, uv + (vec2(-halfpixel.x, halfpixel.y) * localInfo.offset)) * 2.0);\n"
	"    sum += texture(texture0, uv + (vec2(0.0, halfpixel.y * 2.0) * localInfo.offset));\n"
	"    sum += (texture(texture0, uv + (vec2(halfpixel.x, halfpixel.y) * localInfo.offset)) * 2.0);\n"
	"    sum += texture(texture0, uv + (vec2(halfpixel.x * 2.0, 0.0) * localInfo.offset));\n"
	"    sum += (texture(texture0, uv + (vec2(halfpixel.x, -halfpixel.y) * localInfo.offset)) * 2.0);\n"
	"    sum += texture(texture0, uv + (vec2(0.0, (-halfpixel.y) * 2.0) * localInfo.offset));\n"
	"    sum += (texture(texture0, uv + (vec2(-halfpixel.x, -halfpixel.y) * localInfo.offset)) * 2.0);\n"
	"    FragColor = sum / vec4(12.0);\n"
	"}\n"
;