// This file is automatically generated, please do not alter it.
// 2025-10-28 17:33:33
#pragma once

inline auto DUAL_KAWASE_BLUR_UP_SAMPLE_PASS_FRAG_STR =
	"#version 420"
	"layout(binding = 1, std140) uniform LocalInfo"
	"{"
	"    vec2 iResolution;"
	"    vec2 offset;"
	"} localInfo;"
	"layout(binding = 0) uniform sampler2D texture0;"
	"layout(location = 0) out vec4 FragColor;"
	"void main()"
	"{"
	"    vec2 uv = gl_FragCoord.xy / localInfo.iResolution;"
	"    vec2 halfpixel = vec2(0.5) / localInfo.iResolution;"
	"    vec4 sum = texture(texture0, uv + (vec2((-halfpixel.x) * 2.0, 0.0) * localInfo.offset));"
	"    sum += (texture(texture0, uv + (vec2(-halfpixel.x, halfpixel.y) * localInfo.offset)) * 2.0);"
	"    sum += texture(texture0, uv + (vec2(0.0, halfpixel.y * 2.0) * localInfo.offset));"
	"    sum += (texture(texture0, uv + (vec2(halfpixel.x, halfpixel.y) * localInfo.offset)) * 2.0);"
	"    sum += texture(texture0, uv + (vec2(halfpixel.x * 2.0, 0.0) * localInfo.offset));"
	"    sum += (texture(texture0, uv + (vec2(halfpixel.x, -halfpixel.y) * localInfo.offset)) * 2.0);"
	"    sum += texture(texture0, uv + (vec2(0.0, (-halfpixel.y) * 2.0) * localInfo.offset));"
	"    sum += (texture(texture0, uv + (vec2(-halfpixel.x, -halfpixel.y) * localInfo.offset)) * 2.0);"
	"    FragColor = sum / vec4(12.0);"
	"}"
;