// This file is automatically generated, please do not alter it.
// 2025-10-28 17:33:33
#pragma once

inline auto DUAL_KAWASE_BLUR_DOWN_SAMPLE_PASS_FRAG_STR =
	"#version 310 es"
	"precision mediump float;"
	"precision highp int;"
	"layout(binding = 1, std140) uniform LocalInfo"
	"{"
	"    highp vec2 iResolution;"
	"    highp vec2 offset;"
	"} localInfo;"
	"layout(binding = 0) uniform highp sampler2D texture0;"
	"layout(location = 0) out highp vec4 FragColor;"
	"void main()"
	"{"
	"    highp vec2 uv = gl_FragCoord.xy / localInfo.iResolution;"
	"    highp vec2 halfpixel = vec2(0.5) / localInfo.iResolution;"
	"    highp vec4 sum = texture(texture0, uv) * 4.0;"
	"    sum += texture(texture0, uv - (halfpixel * localInfo.offset));"
	"    sum += texture(texture0, uv + (halfpixel * localInfo.offset));"
	"    sum += texture(texture0, uv + (vec2(halfpixel.x, -halfpixel.y) * localInfo.offset));"
	"    sum += texture(texture0, uv - (vec2(halfpixel.x, -halfpixel.y) * localInfo.offset));"
	"    FragColor = sum / vec4(8.0);"
	"}"
;