// This file is automatically generated, please do not alter it.
// 2025-10-27 15:10:18
#pragma once

inline auto GAUSSIAN_BLUR_PASS_COMP_STR =
	"#version 310 es"
	"layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;"
	"layout(binding = 0, rgba8) uniform readonly highp image2D inputImage;"
	"layout(binding = 1, rgba8) uniform writeonly highp image2D outputImage;"
	"void main()"
	"{"
	"    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);"
	"    vec4 color = imageLoad(inputImage, coord);"
	"    float gray = dot(color.xyz, vec3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625));"
	"    imageStore(outputImage, coord, vec4(gray, gray, gray, color.w));"
	"}"
;