// This file is automatically generated, please do not alter it.
// 2025-12-14 00:38:42
#pragma once

inline auto SWIRL_WARP_EFFECT_FRAG_STR =
	"#version 410\n"
	"layout(std140) uniform LocalInfo\n"
	"{\n"
	"    float radius;\n"
	"    float angle;\n"
	"    vec2 center;\n"
	"} localInfo;\n"
	"uniform sampler2D uTex;\n"
	"layout(location = 0) in vec2 texCoord;\n"
	"layout(location = 0) out vec4 FragColor;\n"
	"void main()\n"
	"{\n"
	"    vec2 texSize = vec2(textureSize(uTex, 0));\n"
	"    float effectRadius = localInfo.radius / texSize.y;\n"
	"    float effectAngle = localInfo.angle;\n"
	"    vec2 center = localInfo.center / texSize;\n"
	"    vec2 uv = texCoord - center;\n"
	"    float len = length(uv * vec2(texSize.x / texSize.y, 1.0));\n"
	"    float angle = atan(uv.y, uv.x) + (effectAngle * smoothstep(effectRadius, 0.0, len));\n"
	"    float radius = length(uv);\n"
	"    vec2 cood = vec2(radius * cos(angle), radius * sin(angle)) + center;\n"
	"    FragColor = texture(uTex, cood);\n"
	"}\n"
;