// This file is automatically generated, please do not alter it.
// 2025-11-02 13:29:46
#pragma once

inline auto DUAL_KAWASE_BLUR_UP_SAMPLE_PASS_FRAG_STR =
	"#version 310 es\n"
	"precision mediump float;\n"
	"precision highp int;\n"
	"layout(binding = 1, std140) uniform LocalInfo\n"
	"{\n"
	"    highp vec2 iResolution;\n"
	"    highp vec2 offset;\n"
	"} localInfo;\n"
	"layout(binding = 0) uniform highp sampler2D texture0;\n"
	"layout(location = 0) out highp vec4 FragColor;\n"
	"void main()\n"
	"{\n"
	"    highp vec2 uv = gl_FragCoord.xy / localInfo.iResolution;\n"
	"    highp vec2 halfpixel = vec2(0.5) / localInfo.iResolution;\n"
	"    highp vec4 sum = texture(texture0, uv + (vec2((-halfpixel.x) * 2.0, 0.0) * localInfo.offset));\n"
	"    sum += (texture(texture0, uv + (vec2(-halfpixel.x, halfpixel.y) * localInfo.offset)) * 2.0);\n"
	"    sum += texture(texture0, uv + (vec2(0.0, halfpixel.y * 2.0) * localInfo.offset));\n"
	"    sum += (texture(texture0, uv + (vec2(halfpixel.x, halfpixel.y) * localInfo.offset)) * 2.0);\n"
	"    sum += texture(texture0, uv + (vec2(halfpixel.x * 2.0, 0.0) * localInfo.offset));\n"
	"    sum += (texture(texture0, uv + (vec2(halfpixel.x, -halfpixel.y) * localInfo.offset)) * 2.0);\n"
	"    sum += texture(texture0, uv + (vec2(0.0, (-halfpixel.y) * 2.0) * localInfo.offset));\n"
	"    sum += (texture(texture0, uv + (vec2(-halfpixel.x, -halfpixel.y) * localInfo.offset)) * 2.0);\n"
	"    FragColor = sum / vec4(12.0);\n"
	"}\n"
;