// This file is automatically generated, please do not alter it.
// 2025-09-07 12:17:26
#pragma once

inline auto DUAL_KAWASE_BLUR_UP_SAMPLE_PASS_VERT_STR =
	"#version 310 es"
	"layout(location = 0) in vec2 vPos;"
	"void main()"
	"{"
	"    gl_Position = vec4(vPos, 1.0, 1.0);"
	"}"
;