// This file is automatically generated, please do not alter it.
// 2025-12-07 17:10:50
#pragma once

inline auto DUAL_KAWASE_BLUR_DOWN_SAMPLE_PASS_VERT_STR =
	"#version 410\n"
	"layout(location = 0) in vec2 vPos;\n"
	"void main()\n"
	"{\n"
	"    gl_Position = vec4(vPos, 1.0, 1.0);\n"
	"    gl_Position.y = -gl_Position.y;\n"
	"}\n"
;