// This file is automatically generated, please do not alter it.
// 2025-12-14 00:38:42
#pragma once

inline auto ALPHA_MASK_PASS_FRAG_STR =
	"#version 310 es\n"
	"precision mediump float;\n"
	"precision highp int;\n"
	"layout(binding = 1, std140) uniform LocalInfo\n"
	"{\n"
	"    highp vec3 shadowColor;\n"
	"    highp float shadowAlpha;\n"
	"} localInfo;\n"
	"layout(binding = 0) uniform highp sampler2D targetTex;\n"
	"layout(location = 0) in highp vec2 vUV;\n"
	"layout(location = 0) out highp vec4 FragColor;\n"
	"void main()\n"
	"{\n"
	"    highp vec4 src = texture(targetTex, vUV);\n"
	"    highp float a = src.w;\n"
	"    FragColor = vec4(localInfo.shadowColor, localInfo.shadowAlpha * a);\n"
	"}\n"
;