// This file is automatically generated, please do not alter it.
// 2025-12-14 00:38:42
#pragma once

inline auto SHADOW_EFFECT_PASS_FRAG_STR =
	"#version 310 es\n"
	"precision mediump float;\n"
	"precision highp int;\n"
	"layout(binding = 2, std140) uniform LocalInfo\n"
	"{\n"
	"    highp vec2 shadowOffset;\n"
	"} localInfo;\n"
	"layout(binding = 1) uniform highp sampler2D alphaTex;\n"
	"layout(binding = 0) uniform highp sampler2D targetTex;\n"
	"layout(location = 0) in highp vec2 vUV;\n"
	"layout(location = 0) out highp vec4 FragColor;\n"
	"void main()\n"
	"{\n"
	"    highp vec2 texSize = vec2(textureSize(alphaTex, 0));\n"
	"    highp vec2 shadowUV = vUV - (localInfo.shadowOffset * (vec2(1.0) / texSize));\n"
	"    highp vec4 shadowCol = texture(alphaTex, shadowUV);\n"
	"    highp vec4 src = texture(targetTex, vUV);\n"
	"    FragColor = (src * src.w) + (shadowCol * (1.0 - src.w));\n"
	"}\n"
;