// This file is automatically generated, please do not alter it.
// 2025-12-06 14:26:45
#pragma once

inline auto LIQUIFY_IMAGE_PASS_FRAG_STR =
	"#version 310 es\n"
	"precision mediump float;\n"
	"precision highp int;\n"
	"layout(binding = 2) uniform highp sampler2D uvReadTex;\n"
	"layout(binding = 1) uniform highp sampler2D targetTex;\n"
	"layout(location = 0) in highp vec2 texCoord;\n"
	"layout(location = 0) out highp vec4 FragColor;\n"
	"void main()\n"
	"{\n"
	"    highp vec2 uv = texture(uvReadTex, texCoord).xy;\n"
	"    FragColor = texture(targetTex, uv);\n"
	"}\n"
;