// This file is automatically generated, please do not alter it.
// 2025-12-14 00:38:42
#pragma once

inline auto LIQUIFY_MAIN_PASS_VERT_STR =
	"#version 310 es\n"
	"layout(location = 0) in vec2 vPos;\n"
	"layout(location = 0) out vec2 texCoord;\n"
	"layout(location = 1) in vec2 vTexCoord;\n"
	"void main()\n"
	"{\n"
	"    gl_Position = vec4(vPos.x, vPos.y, 0.0, 1.0);\n"
	"    texCoord = vTexCoord;\n"
	"    gl_Position.y = -gl_Position.y;\n"
	"}\n"
;