// This file is automatically generated, please do not alter it.
// 2025-12-06 14:26:45
#pragma once

inline auto LIQUIFY_IMAGE_PASS_FRAG_STR =
	"#version 410\n"
	"uniform sampler2D uvReadTex;\n"
	"uniform sampler2D targetTex;\n"
	"layout(location = 0) in vec2 texCoord;\n"
	"layout(location = 0) out vec4 FragColor;\n"
	"void main()\n"
	"{\n"
	"    vec2 uv = texture(uvReadTex, texCoord).xy;\n"
	"    FragColor = texture(targetTex, uv);\n"
	"}\n"
;