// This file is automatically generated, please do not alter it.
// 2025-12-14 00:38:42
#pragma once

inline auto ALPHA_MASK_PASS_FRAG_STR =
	"#version 410\n"
	"layout(std140) uniform LocalInfo\n"
	"{\n"
	"    vec3 shadowColor;\n"
	"    float shadowAlpha;\n"
	"} localInfo;\n"
	"uniform sampler2D targetTex;\n"
	"layout(location = 0) in vec2 vUV;\n"
	"layout(location = 0) out vec4 FragColor;\n"
	"void main()\n"
	"{\n"
	"    vec4 src = texture(targetTex, vUV);\n"
	"    float a = src.w;\n"
	"    FragColor = vec4(localInfo.shadowColor, localInfo.shadowAlpha * a);\n"
	"}\n"
;