// This file is automatically generated, please do not alter it.
// 2025-12-14 00:38:42
#pragma once

inline auto SHADOW_EFFECT_PASS_FRAG_STR =
	"#version 410\n"
	"layout(std140) uniform LocalInfo\n"
	"{\n"
	"    vec2 shadowOffset;\n"
	"} localInfo;\n"
	"uniform sampler2D alphaTex;\n"
	"uniform sampler2D targetTex;\n"
	"layout(location = 0) in vec2 vUV;\n"
	"layout(location = 0) out vec4 FragColor;\n"
	"void main()\n"
	"{\n"
	"    vec2 texSize = vec2(textureSize(alphaTex, 0));\n"
	"    vec2 shadowUV = vUV - (localInfo.shadowOffset * (vec2(1.0) / texSize));\n"
	"    vec4 shadowCol = texture(alphaTex, shadowUV);\n"
	"    vec4 src = texture(targetTex, vUV);\n"
	"    FragColor = (src * src.w) + (shadowCol * (1.0 - src.w));\n"
	"}\n"
;