// This file is automatically generated, please do not alter it.
// 2025-07-06 17:42:54
#pragma once

inline auto SCREEN_PASS_FRAG_STR =
	"#version 420"
	"layout(binding = 1) uniform sampler2D screenTex;"
	"layout(location = 0) out vec4 FragColor;"
	"layout(location = 0) in vec2 vTexCoord;"
	"void main()"
	"{"
	"    FragColor = texture(screenTex, vTexCoord);"
	"}"
;