// This file is automatically generated, please do not alter it.
// 2025-11-25 21:22:52
#pragma once

inline auto SCREEN_PASS_VERT_STR =
	"#version 410\n"
	"layout(std140) uniform LocalInfo\n"
	"{\n"
	"    vec2 screenSize;\n"
	"} localInfo;\n"
	"layout(std140) uniform GlobalInfo\n"
	"{\n"
	"    mat4 view;\n"
	"    mat4 proj;\n"
	"} globalInfo;\n"
	"layout(location = 0) in vec2 vPos;\n"
	"layout(location = 2) in vec2 iOffset;\n"
	"layout(location = 3) in vec2 iSize;\n"
	"layout(location = 0) out vec2 texCoord;\n"
	"layout(location = 1) in vec2 vTexCoord;\n"
	"layout(location = 1) flat out int textureIndex;\n"
	"layout(location = 4) in int iTextureIndex;\n"
	"void main()\n"
	"{\n"
	"    vec2 local = (vPos + vec2(1.0)) * 0.5;\n"
	"    vec2 newPos = iOffset + (local * iSize);\n"
	"    vec2 ndc = ((newPos / localInfo.screenSize) * 2.0) - vec2(1.0);\n"
	"    gl_Position = vec4(ndc.x, ndc.y, 0.0, 1.0);\n"
	"    texCoord = vTexCoord;\n"
	"    textureIndex = iTextureIndex;\n"
	"}\n"
;