// This file is automatically generated, please do not alter it.
// 2025-11-02 13:29:46
#pragma once

inline auto SCREEN_PASS_FRAG_STR =
	"#version 410\n"
	"uniform sampler2D screenTex[1];\n"
	"layout(location = 1) flat in int textureIndex;\n"
	"layout(location = 0) in vec2 texCoord;\n"
	"layout(location = 0) out vec4 FragColor;\n"
	"void main()\n"
	"{\n"
	"    vec4 color;\n"
	"    switch (textureIndex)\n"
	"    {\n"
	"        case 0:\n"
	"        {\n"
	"            color = texture(screenTex[0], texCoord);\n"
	"            break;\n"
	"        }\n"
	"        default:\n"
	"        {\n"
	"            color = vec4(1.0, 0.0, 0.0, 1.0);\n"
	"            break;\n"
	"        }\n"
	"    }\n"
	"    FragColor = color;\n"
	"}\n"
;