// This file is automatically generated, please do not alter it.
// 2025-07-16 22:22:18
#pragma once

inline auto SCREEN_PASS_FRAG_STR =
	"#version 420"
	"layout(binding = 2) uniform sampler2D screenTex[1];"
	"layout(location = 1) flat in int textureIndex;"
	"layout(location = 0) in vec2 texCoord;"
	"layout(location = 0) out vec4 FragColor;"
	"void main()"
	"{"
	"    vec4 color;"
	"    switch (textureIndex)"
	"    {"
	"        case 0:"
	"        {"
	"            color = texture(screenTex[0], texCoord);"
	"            break;"
	"        }"
	"        default:"
	"        {"
	"            color = vec4(1.0, 0.0, 0.0, 1.0);"
	"            break;"
	"        }"
	"    }"
	"    FragColor = color;"
	"}"
;