// This file is automatically generated, please do not alter it.
// 2025-10-28 17:33:33
#pragma once

inline auto GAUSSIAN_BLUR_PASS_COMP_STR =
	"#version 420"
	"#extension GL_ARB_compute_shader : require"
	"layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;"
	"layout(binding = 1, rgba8) uniform writeonly image2D outputImage;"
	"void main()"
	"{"
	"    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);"
	"}"
;