// This file is automatically generated, please do not alter it.
// 2025-11-25 21:22:52
#pragma once

inline auto GAUSSIAN_BLUR_PASS_COMP_STR =
	"#version 410\n"
	"#extension GL_ARB_compute_shader : require\n"
	"#extension GL_ARB_shader_image_load_store : require\n"
	"layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;\n"
	"layout(rgba8) uniform writeonly image2D outputImage;\n"
	"void main()\n"
	"{\n"
	"    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);\n"
	"}\n"
;