// This file is automatically generated, please do not alter it.
// 2025-10-28 17:33:33
#pragma once

inline auto SCREEN_PASS_VERT_STR =
	"#version 310 es"
	"layout(binding = 1, std140) uniform LocalInfo"
	"{"
	"    vec2 screenSize;"
	"} localInfo;"
	"layout(binding = 0, std140) uniform GlobalInfo"
	"{"
	"    mat4 view;"
	"    mat4 proj;"
	"} globalInfo;"
	"layout(location = 0) in vec2 vPos;"
	"layout(location = 2) in vec2 iOffset;"
	"layout(location = 3) in vec2 iSize;"
	"layout(location = 0) out vec2 texCoord;"
	"layout(location = 1) in vec2 vTexCoord;"
	"layout(location = 1) flat out int textureIndex;"
	"layout(location = 4) in int iTextureIndex;"
	"void main()"
	"{"
	"    vec2 local = (vPos + vec2(1.0)) * 0.5;"
	"    vec2 newPos = iOffset + (local * iSize);"
	"    vec2 ndc = ((newPos / localInfo.screenSize) * 2.0) - vec2(1.0);"
	"    gl_Position = vec4(ndc.x, ndc.y, 0.0, 1.0);"
	"    texCoord = vTexCoord;"
	"    textureIndex = iTextureIndex;"
	"}"
;