#pragma once
// This file is automatically generated, please do not alter it.
// 2025-06-28 21:23:46

inline auto SCREEN_PASS_FRAG =
"#version 310 es"
"precision mediump float;"
"precision highp int;"
"layout(binding = 1) uniform highp sampler2D screenTex;"
"layout(location = 0) out highp vec4 FragColor;"
"layout(location = 0) in highp vec2 vTexCoord;"
"void main()"
"{"
"    FragColor = texture(screenTex, vTexCoord);"
"}"
;