// This file is automatically generated, please do not alter it.
// 2025-11-30 15:18:16
#pragma once

inline auto SCREEN_PASS_FRAG_STR =
	"#version 310 es\n"
	"precision mediump float;\n"
	"precision highp int;\n"
	"layout(binding = 2) uniform highp sampler2D screenTex[1];\n"
	"layout(location = 1) flat in int textureIndex;\n"
	"layout(location = 0) in highp vec2 texCoord;\n"
	"layout(location = 0) out highp vec4 FragColor;\n"
	"void main()\n"
	"{\n"
	"    highp vec4 color;\n"
	"    switch (textureIndex)\n"
	"    {\n"
	"        case 0:\n"
	"        {\n"
	"            color = texture(screenTex[0], texCoord);\n"
	"            break;\n"
	"        }\n"
	"        default:\n"
	"        {\n"
	"            color = vec4(1.0, 0.0, 0.0, 1.0);\n"
	"            break;\n"
	"        }\n"
	"    }\n"
	"    FragColor = color;\n"
	"}\n"
;