// This file is automatically generated, please do not alter it.
// 2025-09-07 12:17:26
#pragma once

inline auto ROUND_CORNER_PASS_VERT_STR =
	"#version 420"
	"layout(binding = 0, std140) uniform GlobalInfo"
	"{"
	"    mat4 view;"
	"    mat4 proj;"
	"} globalInfo;"
	"layout(location = 0) in vec2 vPos;"
	"layout(location = 0) out vec2 texCoord;"
	"layout(location = 1) in vec2 vTexCoord;"
	"void main()"
	"{"
	"    gl_Position = (globalInfo.proj * globalInfo.view) * vec4(vPos.x, vPos.y, 0.0, 1.0);"
	"    texCoord = vTexCoord;"
	"}"
;