// This file is automatically generated, please do not alter it.
// 2025-12-06 14:26:45
#pragma once

inline auto ROUND_CORNER_PASS_FRAG_STR =
	"#version 410\n"
	"layout(std140) uniform LocalInfo\n"
	"{\n"
	"    vec2 resolution;\n"
	"} localInfo;\n"
	"uniform sampler2D screenTex;\n"
	"layout(location = 0) out vec4 FragColor;\n"
	"void main()\n"
	"{\n"
	"    FragColor = vec4(0.0, 1.0, 0.0, 1.0);\n"
	"}\n"
;