// This file is automatically generated, please do not alter it.
// 2025-09-07 12:17:26
#pragma once

inline auto ROUND_CORNER_PASS_FRAG_STR =
	"#version 420"
	"layout(binding = 2, std140) uniform LocalInfo"
	"{"
	"    vec2 resolution;"
	"} localInfo;"
	"layout(binding = 1) uniform sampler2D screenTex;"
	"layout(location = 0) out vec4 FragColor;"
	"void main()"
	"{"
	"    FragColor = vec4(0.0, 1.0, 0.0, 1.0);"
	"}"
;