#pragma once
// This file is automatically generated, please do not alter it.
// 2025-06-28 21:23:46

inline auto ROUND_CORNER_PASS_VERT =
"#version 420 es"
"layout(binding = 0, std140) uniform GlobalInfo"
"{"
"    mat4 view;"
"    mat4 proj;"
"} globalInfo;"
"layout(location = 0) in vec2 aPos;"
"layout(location = 0) out vec2 vTexCoord;"
"layout(location = 1) in vec2 aTexCoord;"
"void main()"
"{"
"    gl_Position = (globalInfo.proj * globalInfo.view) * vec4(aPos.x, aPos.y, 0.0, 1.0);"
"    vTexCoord = aTexCoord;"
"}"
;