// This file is automatically generated, please do not alter it.
// 2025-11-02 13:29:46
#pragma once

inline auto ROUND_CORNER_PASS_VERT_STR =
	"#version 410\n"
	"layout(std140) uniform GlobalInfo\n"
	"{\n"
	"    mat4 view;\n"
	"    mat4 proj;\n"
	"} globalInfo;\n"
	"layout(location = 0) in vec2 vPos;\n"
	"layout(location = 0) out vec2 texCoord;\n"
	"layout(location = 1) in vec2 vTexCoord;\n"
	"void main()\n"
	"{\n"
	"    gl_Position = (globalInfo.proj * globalInfo.view) * vec4(vPos.x, vPos.y, 0.0, 1.0);\n"
	"    texCoord = vTexCoord;\n"
	"}\n"
;